### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ankush** [ankush/ankush.dev#1]
- [x] Add date on post and list
- [x] Common nav
- [x] Socials and links
- [x] Redirects 
- [x] Styling
    - [x] List
    - [x] Post
    - [x] Fonts - works fine in firefox, chrome has horrible defaults
- [x] External link icon
- [x] Docker setup
- [x] Static assets - image, resume
- [x] 404
- [x] OG tags
- [x] Dumb rebuild script
- [x] CI
- [x] CD -  `ssh box -t 'bash deploy.sh'`
- [x] RSS
- [x] Syntax highlighting / code
- [x] GFM/Frontmatter refactor
